//! MSI harvest guard: packaging/msi/Package.wxs stays metadata-only and
//! references the auto-generated harvest component group.
//!
//! Two checks, both dependency-free (no WiX toolset needed):
//!
//!   - Package.wxs must not contain a `<File Source=` element. Its presence
//!     means someone reverted to a hand-maintained file list, which silently
//!     omits runtime DLLs added by a CMake install rule.
//!   - Package.wxs must contain `<ComponentGroupRef Id="StagingFiles" />`,
//!     the reference into the auto-generated `_harvest.wxs` fragment. Without
//!     it the Feature ships no files.
//!
//! Cheap enough (no build, no WiX) to run on every pull request.

use std::path::Path;

use regex::Regex;

use super::ValidationReport;

pub fn validate_msi_harvest(repo_root: &Path) -> anyhow::Result<ValidationReport> {
    let wxs_path = repo_root.join("packaging/msi/Package.wxs");
    if !wxs_path.is_file() {
        anyhow::bail!("MSI WXS not found: {}", wxs_path.display());
    }
    let text = std::fs::read_to_string(&wxs_path)?;

    let mut report = ValidationReport::default();

    if Regex::new(r"<File\s+Source=").unwrap().is_match(&text) {
        report.errors.push(
            "packaging/msi/Package.wxs contains a hand-maintained <File Source= element. \
             The file list must be auto-generated by build-release-artifacts.ps1 \
             (New-WixHarvestFragment), not maintained by hand. \
             Remove the <File> elements and let the release script generate _harvest.wxs."
                .into(),
        );
    }

    if !Regex::new(r#"<ComponentGroupRef\s+Id="StagingFiles""#)
        .unwrap()
        .is_match(&text)
    {
        report.errors.push(
            "packaging/msi/Package.wxs is missing <ComponentGroupRef Id=\"StagingFiles\" />. \
             The Feature must reference the harvested component group defined in _harvest.wxs."
                .into(),
        );
    }

    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    const CLEAN_WXS: &str = r#"<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package Name="ExoSnap">
    <Feature Id="MainFeature">
      <ComponentGroupRef Id="StagingFiles" />
    </Feature>
  </Package>
</Wix>
"#;

    fn fixture(wxs: &str) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("packaging/msi")).unwrap();
        std::fs::write(dir.path().join("packaging/msi/Package.wxs"), wxs).unwrap();
        dir
    }

    #[test]
    fn a_metadata_only_package_referencing_staging_files_passes() {
        let dir = fixture(CLEAN_WXS);
        let report = validate_msi_harvest(dir.path()).unwrap();
        assert!(report.ok(), "{:?}", report.errors);
    }

    #[test]
    fn a_missing_package_wxs_is_a_hard_error() {
        let dir = tempfile::tempdir().unwrap();
        let error = validate_msi_harvest(dir.path()).unwrap_err();
        assert!(error.to_string().contains("MSI WXS not found"));
    }

    #[test]
    fn a_hand_maintained_file_element_is_rejected() {
        let dir = fixture(&format!(
            "{}\n<File Source=\"bin\\exosnap.exe\" />\n",
            CLEAN_WXS
        ));
        let report = validate_msi_harvest(dir.path()).unwrap();
        assert!(!report.ok());
        assert!(
            report
                .errors
                .iter()
                .any(|e| e.contains("hand-maintained <File Source= element"))
        );
    }

    #[test]
    fn a_missing_staging_files_reference_is_rejected() {
        let dir = fixture(&CLEAN_WXS.replace("<ComponentGroupRef Id=\"StagingFiles\" />", ""));
        let report = validate_msi_harvest(dir.path()).unwrap();
        assert!(!report.ok());
        assert!(
            report
                .errors
                .iter()
                .any(|e| e.contains("missing <ComponentGroupRef"))
        );
    }

    #[test]
    fn both_violations_are_reported_together() {
        let dir = fixture("<Wix></Wix>");
        let report = validate_msi_harvest(dir.path()).unwrap();
        assert_eq!(report.errors.len(), 1);
        assert!(report.errors[0].contains("missing <ComponentGroupRef"));
    }
}
