<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.333" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

</Project>
