#Requires -Version 7.0
<#
.SYNOPSIS
    The publish lock and the typed harness share one qualification record.

.DESCRIPTION
    Two producers now write `release-verification.json`: the PowerShell campaign in
    `scripts/release-verify.ps1`, and `ExoSnap.Verify` under `tools/release-verify`.
    One reader decides whether either of them may promote a release --
    `scripts/check-release-qualification.ps1`, which the release workflow runs on a
    clean checkout before anything is published.

    Two implementations of a release lock that disagree about a field name is a lock
    that opens. So this feeds a record the C# producer actually wrote through the real
    reader, and asserts both directions: a clean record qualifies, and a record whose
    package digest does not match the bytes the RC published is refused.

    The fixture is generated by the C# test `WritesTheSampleRecordFixture`, which
    regenerates it on demand and otherwise asserts the producer still writes the shape
    committed here. Nothing in this file writes it: a test that produced its own input
    would be checking a reader against a record no producer emits.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$scriptRoot = Split-Path -Parent $PSScriptRoot
$checker = Join-Path $scriptRoot 'check-release-qualification.ps1'
. (Join-Path $scriptRoot 'lib/ReleaseQualification.ps1')
$fixture = Join-Path $PSScriptRoot 'fixtures/verify-harness/release-verification.sample.json'

. (Join-Path $scriptRoot 'lib/ReleaseQualification.ps1')

# RFC 8032 test vector. This is deliberately public test material, never a release key.
$script:TestSigningKey = 'nWGxne/9WmC6hEr0kuwsxERJxWl7MmkZcDusAxyuf2A='
$script:TestPublicKey = 'd75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a'

$script:Passed = 0
$script:Failed = 0
$script:Skipped = 0

function Test-Case {
    param([Parameter(Mandatory)] [string] $Name, [Parameter(Mandatory)] [scriptblock] $Body)
    try {
        & $Body
        Write-Host "  PASS  $Name" -ForegroundColor Green
        $script:Passed++
    }
    catch {
        Write-Host "  FAIL  $Name" -ForegroundColor Red
        Write-Host "        $($_.Exception.Message)" -ForegroundColor Red
        $script:Failed++
    }
}

function Assert-True { param($Condition, [string] $Message) if (-not $Condition) { throw $Message } }
function Assert-Equal {
    param($Expected, $Actual, [string] $Message)
    if ("$Expected" -ne "$Actual") { throw "$Message (expected '$Expected', got '$Actual')" }
}

function Invoke-Checker {
    <#
    .SYNOPSIS
        Runs the publish lock against a record and returns its exit code and output.
    .DESCRIPTION
        A separate pwsh, not a dot-source: the checker calls `exit`, and the whole
        point of the lock is what that exit code says. Running it in-process would
        end this test file at the first verdict.

        The committed fixture is C# producer output and must not be rewritten by this
        test. Copy its exact bytes to a temporary location, sign that copy with the
        published RFC 8032 test key, and feed the signed copy to the real publish lock.
    #>
    param(
        [Parameter(Mandatory)] [string] $RecordPath,
        [string] $ExpectedCommit,
        [string] $ExpectedRcTag,
        [string] $Sha256Directory
    )

    $directory = Join-Path ([IO.Path]::GetTempPath()) (
        "exosnap-signed-record-" + [guid]::NewGuid().ToString('n'))
    New-Item -ItemType Directory -Path $directory -Force | Out-Null

    try {
        $signedRecord = Join-Path $directory 'release-verification.json'
        Copy-Item -LiteralPath $RecordPath -Destination $signedRecord

        New-ReleaseQualificationSignatureFile `
            -RecordPath $signedRecord `
            -SigningKeyBase64 $script:TestSigningKey | Out-Null

        $arguments = @(
            '-NoProfile',
            '-NonInteractive',
            '-File', $checker,
            '-RecordPath', $signedRecord,
            '-PublicKeyHex', $script:TestPublicKey
        )
        if ($ExpectedCommit) { $arguments += @('-ExpectedCommit', $ExpectedCommit) }
        if ($ExpectedRcTag) { $arguments += @('-ExpectedRcTag', $ExpectedRcTag) }
        if ($Sha256Directory) { $arguments += @('-Sha256Directory', $Sha256Directory) }

        $output = & pwsh @arguments 2>&1 | Out-String
        return @{ ExitCode = $LASTEXITCODE; Output = $output }
    }
    finally {
        Remove-Item -LiteralPath $directory -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function New-SidecarDirectory {
    <#
    .SYNOPSIS
        A throwaway directory of `.sha256` sidecars in the sha256sum convention.
    #>
    param([Parameter(Mandatory)] [hashtable] $Hashes)

    $directory = Join-Path ([IO.Path]::GetTempPath()) ("exosnap-record-" + [guid]::NewGuid().ToString('n'))
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
    foreach ($name in $Hashes.Keys) {
        Set-Content -LiteralPath (Join-Path $directory "$name.sha256") `
            -Value "$($Hashes[$name])  $name" -Encoding utf8NoBOM
    }
    return $directory
}

Write-Host ''
Write-Host 'The C# producer and the publish lock share one record'

if (-not (Test-Path -LiteralPath $fixture -PathType Leaf)) {
    # Reported, never passed over. A missing fixture means the shared contract was
    # not checked at all, and a suite that stayed green through that would be the
    # reason nobody noticed.
    Write-Host "  SKIP  the C#-produced sample record is missing: $fixture" -ForegroundColor Yellow
    Write-Host '        regenerate it with EXOSNAP_WRITE_VERIFY_FIXTURES=1 dotnet test tools/release-verify'
    $script:Skipped++
    Write-Host ''
    Write-Host "0/0 passed, 1 skipped"
    exit 0
}

$record = Get-Content -LiteralPath $fixture -Raw | ConvertFrom-Json
$packages = @($record.packages)
$package = $packages[0]

Test-Case 'the sample record is the shape the lock understands' {
    Assert-Equal 'exosnap.release-verification/1' $record.schema 'the record must carry the shared schema id'
    Assert-Equal 'QUALIFIED' $record.qualification.overall 'the sample must be a qualified record'
    Assert-True ($packages.Count -ge 1) 'the record must describe at least one published package'
    Assert-True (-not [string]::IsNullOrWhiteSpace($package.sha256)) 'the package must carry a digest'
}

Test-Case 'a clean C#-produced record satisfies every content rule the lock has' {
    # The content rules only -- every field the two implementations have to agree
    # about -- and deliberately not the completeness rule. That one compares the
    # record against the catalog and policy of the source line being published,
    # and the C# producer writes a catalog identity of its own ("catalog-1"), so
    # it would refuse this fixture whatever the field names were. The case below
    # is about that refusal; this one is about the field names.
    $blockers = @(Get-ReleaseQualificationBlockers -Record $record)
    Assert-Equal 0 $blockers.Count `
        "the lock objected to a clean record's content: $($blockers -join '; ')"
}

Test-Case 'the C#-produced record cannot promote this source line yet' {
    # Not a defect in either half: the C# producer does not yet write this
    # repository's scenario catalog, and a record about a different set of gates
    # is not a qualification of this one. Stated as a test so the cutover cannot
    # be declared finished while it is still true.
    $sidecars = New-SidecarDirectory -Hashes @{ $package.fileName = $package.sha256 }
    try {
        $result = Invoke-Checker -RecordPath $fixture -ExpectedCommit $record.sourceCommit `
            -ExpectedRcTag $record.rcTag -Sha256Directory $sidecars
        Assert-Equal 1 $result.ExitCode 'a record about another catalog must not promote this commit'
        Assert-True ($result.Output -match "this source line's catalog") `
            "the refusal must say the catalog is not this one: $($result.Output)"
    }
    finally { Remove-Item -LiteralPath $sidecars -Recurse -Force -ErrorAction SilentlyContinue }
}

Test-Case 'a record whose package digest is not the published one is refused' {
    # The single most important comparison the lock makes: the campaign has to have
    # run against the bytes the release page actually serves. One flipped hex digit
    # is the whole difference between a verdict about this release and a verdict
    # about a build nobody published.
    $published = ($package.sha256.Substring(0, 63) + $(if ($package.sha256[63] -eq 'a') { 'b' } else { 'a' }))
    $sidecars = New-SidecarDirectory -Hashes @{ $package.fileName = $published }
    try {
        $result = Invoke-Checker -RecordPath $fixture -ExpectedCommit $record.sourceCommit `
            -ExpectedRcTag $record.rcTag -Sha256Directory $sidecars
        Assert-Equal 1 $result.ExitCode 'the lock must refuse a record about different bytes'
        Assert-True ($result.Output -match [regex]::Escape($package.fileName)) `
            'the refusal must name the package whose digest did not match'
    }
    finally { Remove-Item -LiteralPath $sidecars -Recurse -Force -ErrorAction SilentlyContinue }
}

Test-Case 'a record about a different commit is refused' {
    $sidecars = New-SidecarDirectory -Hashes @{ $package.fileName = $package.sha256 }
    try {
        $result = Invoke-Checker -RecordPath $fixture -ExpectedCommit ('f' * 40) `
            -ExpectedRcTag $record.rcTag -Sha256Directory $sidecars
        Assert-Equal 1 $result.ExitCode 'the lock must refuse a record about another commit'
        Assert-True ($result.Output -match 'the tag points at') 'the refusal must say which commit was expected'
    }
    finally { Remove-Item -LiteralPath $sidecars -Recurse -Force -ErrorAction SilentlyContinue }
}

Test-Case 'the RC published a package the record never describes' {
    $sidecars = New-SidecarDirectory -Hashes @{ 'ExoSnap-never-measured.msi' = ('0' * 64) }
    try {
        $result = Invoke-Checker -RecordPath $fixture -ExpectedCommit $record.sourceCommit `
            -ExpectedRcTag $record.rcTag -Sha256Directory $sidecars
        Assert-Equal 1 $result.ExitCode 'a package nobody measured must block the promotion'
        Assert-True ($result.Output -match 'did not run against the published assets') `
            'the refusal must say the campaign never saw the asset'
    }
    finally { Remove-Item -LiteralPath $sidecars -Recurse -Force -ErrorAction SilentlyContinue }
}

Write-Host ''
Write-Host "$script:Passed/$($script:Passed + $script:Failed) passed"
if ($script:Failed -gt 0) { exit 1 }
exit 0
