#pragma once

// The brand mark suite, as the running theme's colours.
//
// The assets in `app/assets/brand/marks` are the designer cut, authored in a
// fixed reference palette (see ui/brand/BrandMark.h). Shipping them unmodified
// would mean a tray icon that ignores the user's accent and a light-theme mark
// with a dark theme's ring weight, so every consumer loads them through here:
// the shapes come from the asset, the colours from the theme, and the optical
// correction from the size the raster will be.
//
// The transform is a string substitution rather than an XML pass. The suite is
// generated by one script and its vocabulary is therefore known -- four colours,
// one opacity, strokes and upright bars -- and a DOM would buy a generality
// nothing needs at the cost of a parse per icon. Every value it does not
// recognise is left alone, and `brand_geometry_tests` asserts there are none.

#include <QByteArray>
#include <QColor>
#include <QString>

#include "ui/brand/BrandMark.h"

namespace exosnap::ui::brand {

// Every drawing the suite ships. Wider than the shell's state enum on purpose:
// this is the asset inventory, and which of these a product state may show is a
// decision models/ShellPresence.h makes, not this file.
enum class BrandMarkKind {
    // The product's identity. What the application icon is derived from.
    Brand,
    Idle,
    Recording,
    Processing,
    Paused,
    Saved,
    Warning,
    Error,
};

// Frames each animated mark ships. The two sequences differ: the recording beat
// rests at the bottom of its loop for two ticks, which is what makes it read as
// a heartbeat rather than as a metronome, and the processing arc has no rest.
//
// The cadence belongs to models/RecordingPulse.h; this is only how many files
// there are.
inline constexpr int kRecordingMarkFrameCount = 6;
inline constexpr int kProcessingMarkFrameCount = 4;

// Whether `kind` is a sequence rather than a single drawing.
[[nodiscard]] bool BrandMarkIsAnimated(BrandMarkKind kind) noexcept;

// How many frames `kind` has. One for a static drawing, so a caller can index
// it without asking whether it is animated first.
[[nodiscard]] int BrandMarkFrameCount(BrandMarkKind kind) noexcept;

// The Qt resource path of one drawing. `frame` is ignored for a static kind and
// wrapped into range for an animated one, so an out-of-date frame counter cannot
// produce a missing-resource icon.
[[nodiscard]] QString BrandMarkAssetPath(BrandMarkKind kind, int frame = 0);

// The colours a mark is rendered in. Resolved by the caller, because the shell
// renderer and the in-application mark must resolve them exactly once and from
// the same table.
struct BrandMarkPalette {
    QColor accent;
    QColor recording;
    QColor caution;
    QColor success;
    // The outer ring's opacity BEFORE the optical profile scales it. Dark and
    // light differ here and nowhere else.
    double outer_opacity = kOuterOpacityDark;
};

// One themed mark, ready for QSvgRenderer. Returns an empty array only if the
// resource is missing, which is a build defect rather than a runtime condition.
[[nodiscard]] QByteArray ThemedBrandMarkSvg(BrandMarkKind kind, int frame, const BrandMarkPalette& palette,
                                            const OpticalProfile& profile);

} // namespace exosnap::ui::brand
