// test_updater_exit_codes.cpp -- what the updater process tells its caller.
//
// Two halves, both necessary:
//   * the pure mapping from a flow state to an exit code, covered for every
//     phase, so "a failed update exits non-zero" is a property of the table
//     rather than of one lucky path;
//   * the two codes a real launch can produce before any window exists, checked
//     by actually running the shipped executable. That half is what proves the
//     contract survives main()'s early returns -- the exact place the historic
//     "always 0" lived.

#include <gtest/gtest.h>

#include <QProcess>
#include <QString>
#include <QStringList>

#include "UpdaterExitCode.h"
// Generated by apps/updater/tests/CMakeLists.txt: EXOSNAP_UPDATER_EXE as a raw
// string literal, so the build-tree path never appears in the source tree.
#include "UpdaterExePath.h"

namespace {

using exosnap::update::FailureCase;
using exosnap::update::UpdateFlowState;
using exosnap::update::UpdatePhase;

int ExitFor(UpdatePhase phase) {
    UpdateFlowState state;
    state.phase = phase;
    return UpdaterExitCodeFor(state);
}

TEST(UpdaterExitCode, CompletedIsSuccess) {
    EXPECT_EQ(ExitFor(UpdatePhase::Completed), static_cast<int>(UpdaterExit::Success));
}

TEST(UpdaterExitCode, SoftSuccessIsStillSuccess) {
    // B4: installed and verified, only the automatic relaunch did not open. The
    // update DID apply, and a caller told otherwise would be wrong about the
    // machine.
    UpdateFlowState state;
    state.phase = exosnap::update::PhaseForFailure(FailureCase::LaunchFailed);
    state.failure_case = FailureCase::LaunchFailed;
    EXPECT_EQ(UpdaterExitCodeFor(state), static_cast<int>(UpdaterExit::Success));
}

TEST(UpdaterExitCode, FailedIsNonZero) {
    EXPECT_EQ(ExitFor(UpdatePhase::Failed), static_cast<int>(UpdaterExit::UpdateFailed));
    EXPECT_NE(ExitFor(UpdatePhase::Failed), static_cast<int>(UpdaterExit::Success));
}

TEST(UpdaterExitCode, EveryFailureCaseThatEndsFailedExitsNonZero) {
    // The property that matters, stated over the whole matrix: there is no
    // visible failure that leaves the process claiming success.
    for (const FailureCase failure :
         {FailureCase::DownloadFailed, FailureCase::VerifyDownloadFailed, FailureCase::VerifyReinstallMismatch,
          FailureCase::TargetVersionMismatch, FailureCase::AppWontClose, FailureCase::InstallFailed,
          FailureCase::VerifyInstallFailed, FailureCase::RestoreFailed, FailureCase::VerifyInstallFailedMsi,
          FailureCase::UacDeclined, FailureCase::MsiFailed}) {
        UpdateFlowState state;
        state.phase = exosnap::update::PhaseForFailure(failure);
        state.failure_case = failure;
        EXPECT_EQ(UpdaterExitCodeFor(state), static_cast<int>(UpdaterExit::UpdateFailed))
            << "case " << exosnap::update::FailureCaseName(failure);
    }
}

TEST(UpdaterExitCode, RebootRequiredIsItsOwnCode) {
    // C3 applied the upgrade and needs a machine restart. Folding it into 0
    // would hide an outstanding action; folding it into 1 would report a
    // successful install as a failure.
    UpdateFlowState state;
    state.phase = exosnap::update::PhaseForFailure(FailureCase::MsiRebootRequired);
    state.failure_case = FailureCase::MsiRebootRequired;
    state.reboot_required = true;
    const int code = UpdaterExitCodeFor(state);
    EXPECT_EQ(code, static_cast<int>(UpdaterExit::RebootRequired));
    EXPECT_NE(code, static_cast<int>(UpdaterExit::Success));
    EXPECT_NE(code, static_cast<int>(UpdaterExit::UpdateFailed));
}

TEST(UpdaterExitCode, UpToDateIsNeitherSuccessNorFailure) {
    const int code = ExitFor(UpdatePhase::UpToDate);
    EXPECT_EQ(code, static_cast<int>(UpdaterExit::UpToDate));
    EXPECT_NE(code, static_cast<int>(UpdaterExit::Success));
    EXPECT_NE(code, static_cast<int>(UpdaterExit::UpdateFailed));
}

TEST(UpdaterExitCode, AnIntentionalCancellationIsNotAFailure) {
    // A user who stops a download must not make a release script report a failed
    // update. It shares the code with "closed without an outcome", because that
    // is the same statement: nothing installed, nothing broken.
    const int code = ExitFor(UpdatePhase::Cancelled);
    EXPECT_EQ(code, static_cast<int>(UpdaterExit::Cancelled));
    EXPECT_NE(code, static_cast<int>(UpdaterExit::UpdateFailed));
    EXPECT_NE(code, static_cast<int>(UpdaterExit::Success));
}

TEST(UpdaterExitCode, EveryNonTerminalPhaseIsCancelled) {
    for (const UpdatePhase phase : {UpdatePhase::Idle, UpdatePhase::Checking, UpdatePhase::UpdateAvailable,
                                    UpdatePhase::Downloading, UpdatePhase::ReadyToApply, UpdatePhase::WaitingForParent,
                                    UpdatePhase::Applying, UpdatePhase::Verifying, UpdatePhase::Launching}) {
        EXPECT_EQ(ExitFor(phase), static_cast<int>(UpdaterExit::Cancelled)) << exosnap::update::UpdatePhaseName(phase);
    }
}

// -- the real executable -----------------------------------------------------

#ifdef EXOSNAP_UPDATER_EXE

int RunUpdater(const QStringList& arguments) {
    QProcess process;
    process.setProgram(QString::fromUtf8(EXOSNAP_UPDATER_EXE));
    process.setArguments(arguments);
    process.start();
    if (!process.waitForStarted(15000))
        return -1;
    if (!process.waitForFinished(30000)) {
        process.kill();
        (void)process.waitForFinished(5000);
        return -2;
    }
    return process.exitCode();
}

TEST(UpdaterProcessExit, UnknownArgumentIsAUsageError) {
    EXPECT_EQ(RunUpdater({QStringLiteral("--not-a-flag")}), static_cast<int>(UpdaterExit::UsageError));
}

TEST(UpdaterProcessExit, InvalidPreviewStateIsAUsageError) {
    // The preview short-circuit runs before the argument parser, so this exit
    // has its own return statement in main() -- and therefore its own way to
    // regress independently of the parser's.
    EXPECT_EQ(RunUpdater({QStringLiteral("--preview-state"), QStringLiteral("chartreuse")}),
              static_cast<int>(UpdaterExit::UsageError));
}

TEST(UpdaterProcessExit, MissingValueForAPinnedTargetIsAUsageError) {
    EXPECT_EQ(RunUpdater({QStringLiteral("--target-version")}), static_cast<int>(UpdaterExit::UsageError));
}

#endif // EXOSNAP_UPDATER_EXE

} // namespace
