namespace exosnap
{
    [default_interface]
    runtimeclass App : Microsoft.UI.Xaml.Application
    {
        App();
    };

    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    };

    [default_interface]
    runtimeclass AdvancedPage : Microsoft.UI.Xaml.Controls.Page
    {
        AdvancedPage();
    };

    [default_interface]
    runtimeclass AudioPage : Microsoft.UI.Xaml.Controls.Page
    {
        AudioPage();
    };

    [default_interface]
    runtimeclass DiagnosticsPage : Microsoft.UI.Xaml.Controls.Page
    {
        DiagnosticsPage();
    };

    [default_interface]
    runtimeclass HotkeysPage : Microsoft.UI.Xaml.Controls.Page
    {
        HotkeysPage();
    };

    [default_interface]
    runtimeclass LogsPage : Microsoft.UI.Xaml.Controls.Page
    {
        LogsPage();
    };

    [default_interface]
    runtimeclass OutputPage : Microsoft.UI.Xaml.Controls.Page
    {
        OutputPage();
    };

    [default_interface]
    runtimeclass RecordPage : Microsoft.UI.Xaml.Controls.Page
    {
        RecordPage();
    };

    [default_interface]
    runtimeclass VideoPage : Microsoft.UI.Xaml.Controls.Page
    {
        VideoPage();
    };
}
