# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Codexo.ExoSnap
PackageVersion: 0.4.0
InstallerType: wix
Scope: machine
InstallModes:
  - silent
  - silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-06-15
MinimumOSVersion: 10.0.17763.0
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Exoridus/exosnap/releases/download/v0.4.0/ExoSnap-0.4.0-windows-x64.msi
    InstallerSha256: 'F2119D0C1651060EE95E3168CD3031100F3D13838F9221FA98BD1D243E6CC787'
    ProductCode: '{15580765-5C8E-41D6-ABD8-E249B774A165}'
    AppsAndFeaturesEntries:
      - DisplayName: ExoSnap
        Publisher: Codexo
        DisplayVersion: 0.4.0
        ProductCode: '{15580765-5C8E-41D6-ABD8-E249B774A165}'
        UpgradeCode: '{8988DAFC-3AE4-4788-BA6D-62E3F73C7A7D}'
        InstallerType: wix
ManifestType: installer
ManifestVersion: 1.10.0
