using System.Globalization;
using System.Text;
using ExoSnap.Verify.Engine;
using ExoSnap.Verify.Models;

namespace ExoSnap.Verify.Catalog;

/// <summary>
/// Renders the release scenario catalog as a Markdown reference page.
/// </summary>
/// <remarks>
/// The page is a generated artifact checked in under <c>docs/dev</c>. It gives the
/// catalog one readable view instead of several hand-maintained ones, and a test
/// regenerates it and fails when the committed copy has drifted.
///
/// The renderer is a pure function of the catalog: it opens no file and reads no
/// environment, so the CLI and the drift test produce identical bytes. Line
/// endings are always <c>\n</c>, because the committed page is an LF file and the
/// drift comparison is exact.
/// </remarks>
public static class CatalogStatusPage
{
    /// <summary>Repository-relative path of the committed page.</summary>
    public const string RelativePath = "docs/dev/release-verify-catalog.md";

    private const char LineFeed = '\n';

    /// <summary>
    /// Renders the page for a catalog and its migration and promotion state.
    /// </summary>
    /// <param name="catalog">The scenario catalog to describe.</param>
    /// <param name="migratedIds">Ids whose scenario body has been written.</param>
    /// <param name="requiredIds">Ids a campaign must pass before promotion.</param>
    public static string Render(
        ScenarioCatalog catalog,
        IReadOnlyCollection<string> migratedIds,
        IReadOnlyCollection<string> requiredIds)
    {
        ArgumentNullException.ThrowIfNull(catalog);
        ArgumentNullException.ThrowIfNull(migratedIds);
        ArgumentNullException.ThrowIfNull(requiredIds);

        var migrated = new HashSet<string>(migratedIds, StringComparer.OrdinalIgnoreCase);
        var required = new HashSet<string>(requiredIds, StringComparer.OrdinalIgnoreCase);
        var descriptors = catalog.Descriptors;
        var migratedCount = descriptors.Count(descriptor => migrated.Contains(descriptor.Id));

        var page = new StringBuilder();
        Line(page, "# Release verification catalog");
        Line(page);
        Line(page, "<!-- Generated by `ExoSnap.Verify catalog`. Do not edit by hand. -->");
        Line(
            page,
            "<!-- Regenerate: cd tools/release-verify && dotnet run --project ExoSnap.Verify -- " +
            "catalog --out ../../" + RelativePath + " -->");
        Line(page);
        Line(
            page,
            "Every release gate the typed harness knows, in catalog order. " +
            "`docs/dev/release-verify-harness.md` is how to work on the harness and " +
            "`docs/dev/release-verify.md` owns what each gate requires; this page only lays the " +
            "declarations side by side.");
        Line(page);
        Line(
            page,
            $"Catalog version `{catalog.Version}`. " +
            $"{Count(descriptors.Count)} scenarios, {Count(migratedCount)} with a migrated body, " +
            $"{Count(required.Count)} required for promotion.");
        Line(page);
        Line(
            page,
            "| ID | Class | Tier | Layer | Isolation | Privilege | Interaction | Requires | Oracle | " +
            "Migrated | Required | Source |");
        Line(
            page,
            "|----|-------|------|-------|-----------|-----------|-------------|----------|--------|" +
            "----------|----------|--------|");

        foreach (var descriptor in descriptors)
        {
            Line(page, string.Join(
                " | ",
                "| " + Cell(descriptor.Id),
                Cell(descriptor.Class),
                Tier(descriptor.Isolation),
                Cell(descriptor.Layer.ToString()),
                Cell(descriptor.Isolation.ToString()),
                Cell(descriptor.Privilege.ToString()),
                Cell(descriptor.Interaction.ToString()),
                Requirements(descriptor.Requires),
                Cell(descriptor.Oracle.Count == 0 ? "-" : string.Join(", ", descriptor.Oracle)),
                migrated.Contains(descriptor.Id) ? "yes" : "no",
                required.Contains(descriptor.Id) ? "yes" : "no",
                Cell(descriptor.Source) + " |"));
        }

        return page.ToString();
    }

    private static void Line(StringBuilder page, string text = "") => page.Append(text).Append(LineFeed);

    private static string Count(int value) => value.ToString(CultureInfo.InvariantCulture);

    // Isolation is the machine a scenario needs; the tier is the shorthand the
    // harness doc and the checklist use for the same fact.
    private static string Tier(ScenarioIsolation isolation) => isolation switch
    {
        ScenarioIsolation.Hermetic => "0",
        ScenarioIsolation.Desktop => "1",
        ScenarioIsolation.DisposableOs => "2",
        ScenarioIsolation.HardwareLab => "3",
        _ => "-",
    };

    private static string Requirements(IReadOnlyList<CapabilityRequirement> requires) =>
        requires.Count == 0 ? "-" : string.Join("; ", requires.Select(Format));

    private static string Format(CapabilityRequirement requirement) => requirement.Operator switch
    {
        CapabilityOperator.AtLeast => $"{requirement.Key} >= {requirement.Value}",
        CapabilityOperator.NotEquals => $"{requirement.Key} != {requirement.Value}",
        _ => $"{requirement.Key} = {requirement.Value}",
    };

    // A table cell: never empty, and never carrying a character that would break
    // the row it sits in.
    private static string Cell(string value) =>
        string.IsNullOrEmpty(value)
            ? "-"
            : value
                .Replace("\r", string.Empty, StringComparison.Ordinal)
                .Replace("\n", " ", StringComparison.Ordinal)
                .Replace("|", "\\|", StringComparison.Ordinal);
}
