<#
.SYNOPSIS
    Validates that packaging/msi/Package.wxs is metadata-only (no hand-maintained
    file list) and properly references the auto-generated harvest component group.

.DESCRIPTION
    Dependency-free regex/line-based check (no WiX toolset required):

      - Package.wxs must NOT contain any <File Source= element.
        Presence of such an element means someone reverted to a hand-maintained
        file list, which will silently omit runtime DLLs added by CMake install
        rules (the defect that triggered ADR 0036 and this gate).

      - Package.wxs MUST contain <ComponentGroupRef Id="StagingFiles" />.
        This is the reference into the auto-generated _harvest.wxs fragment
        produced by New-WixHarvestFragment in build-release-artifacts.ps1.
        Missing it means the Feature would ship no files.

    This script is intentionally cheap (seconds, no build, no WiX) so it can
    run on every PR in the lint job alongside validate-winget-manifest.ps1.
#>

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$wxsPath  = Join-Path $repoRoot 'packaging/msi/Package.wxs'

$script:Errors = [System.Collections.Generic.List[string]]::new()
function Add-Error { param([string]$Message) $script:Errors.Add($Message) | Out-Null }

# ---------------------------------------------------------------------------
# Existence
# ---------------------------------------------------------------------------
if (-not (Test-Path -LiteralPath $wxsPath -PathType Leaf)) {
    Write-Host "  [FAIL] MSI WXS not found: $wxsPath" -ForegroundColor Red
    exit 1
}

$wxsText = Get-Content -LiteralPath $wxsPath -Raw

# ---------------------------------------------------------------------------
# Guard 1: no hand-maintained <File Source= elements
#
# build-release-artifacts.ps1 generates a companion _harvest.wxs fragment at
# release time (New-WixHarvestFragment) that contains all <Component>/<File>
# entries derived from the pruned cmake --install staging tree. Package.wxs
# must remain metadata-only. If a hand-maintained <File Source= element
# appears here, the file list is static and will silently omit runtime DLLs
# added by future cmake install rules.
# ---------------------------------------------------------------------------
if ($wxsText -match '<File\s+Source=') {
    Add-Error (
        'packaging/msi/Package.wxs contains a hand-maintained <File Source= element. ' +
        'The file list must be auto-generated by build-release-artifacts.ps1 ' +
        '(New-WixHarvestFragment) — not maintained by hand. ' +
        'Remove the <File> elements and let the release script generate _harvest.wxs.'
    )
}

# ---------------------------------------------------------------------------
# Guard 2: Feature must reference the harvested ComponentGroup
#
# The Feature in Package.wxs must reference StagingFiles, which is the master
# ComponentGroup Id defined in the auto-generated _harvest.wxs fragment. If
# this reference is absent the MSI Feature ships no application files.
# ---------------------------------------------------------------------------
if ($wxsText -notmatch '<ComponentGroupRef\s+Id="StagingFiles"') {
    Add-Error (
        'packaging/msi/Package.wxs is missing <ComponentGroupRef Id="StagingFiles" />. ' +
        'The Feature must reference the harvested component group defined in _harvest.wxs.'
    )
}

# ---------------------------------------------------------------------------
# Result
# ---------------------------------------------------------------------------
if ($script:Errors.Count -gt 0) {
    foreach ($e in $script:Errors) { Write-Host "  [FAIL] $e" -ForegroundColor Red }
    Write-Host "MSI harvest validation FAILED ($($script:Errors.Count) error(s))." -ForegroundColor Red
    exit 1
}

Write-Host "MSI harvest validation PASSED (Package.wxs is metadata-only, references StagingFiles)." -ForegroundColor Green
exit 0
